#!/bin/bash
################################################################################
#  rerunclean test [test ...]
#    Rerun failing tests, as defined in STATUS_FAIL in runconfig
#
################################################################################

for subtest in "$@"; do
  echo INFO: Rerunning ${STATUS_FAIL// /,} tests in $subtest
  $MT_MEGATEST -run -target $MT_TARGET -runname $MT_RUNNAME -testpatt $subtest -preclean -rerun ${STATUS_FAIL// /,}
done
