#!/bin/sh
./kill_megatests_in_toppath
if [[ ! -e aside-logs ]]; then mkdir aside-logs; fi
asidedir=aside-logs/`date +%s`
mkdir $asidedir

if [[ -e logs ]]; then
  mv logs $asidedir
  mkdir logs
fi

mv -fv logpro_style.css *.lock logs-aside* NBFAKE-* *.done *.html *.log.gz *.log *.run $asidedir/. 2>/dev/null
