#!/bin/bash
################################################################################
#  rerunclean test [test ...]
#    Rerun failing tests, as defined in STATUS_FAIL in runconfig
#
################################################################################

echo INFO: Rerunning ${STATUS_FAIL// /,} tests
$MT_MEGATEST -rerun-clean -target $MT_TARGET -runname $MT_RUNNAME -testpatt %
