#!/bin/bash
################################################################################
#  rerunclean test [test ...]
#    Rerun failing tests, as defined in STATUS_FAIL in runconfig
#
################################################################################

echo INFO: Rerunning ${STATUS_FAIL// /,} tests
$MT_MEGATEST -run -target $MT_TARGET -runname $MT_RUNNAME -preclean -rerun ${STATUS_FAIL// /,}
