#!/bin/bash
################################################################################
#  set-state-status test [test ...]
#    Toggles state/status for tests 
#
################################################################################


while read t test rest; do

  STATE=COMPLETED

  testpatt=$(echo $test | sed -e 's#(#/#g' -e 's#)##g')
  echo INFO: Updating $test $testpatt

  if [[ $testpatt == toplevel* ]]; then 
    STATUS=${testpatt/toplevel_/}
  else
    STATUS=$(basename $testpatt)
  fi

  case $STATUS in
	$testpatt)          continue ;; # Do not reset passing statuses
    INCOMPLETE|UNKNOWN) STATE=$STATUS ;;
    NOT_STARTED)        STATE=NOT_STARTED; STATUS=n/a ;;
  esac

  echo INFO: Set state/status to $STATE,$STATUS for $testpatt
  $MT_MEGATEST -set-state-status $STATE,$STATUS -runname $MT_RUNNAME -testpatt $testpatt

done < <($MT_MEGATEST -list-runs $MT_RUNNAME | grep Test:)

