#!/bin/bash
################################################################################
#  set-state-status test [test ...]
#    Toggles state/status for tests 
#
################################################################################

echo DEBUG: STATUS_PASS=$STATUS_PASS
echo DEBUG: STATUS_FAIL=$STATUS_FAIL
echo

while read t test rest; do

  STATE=COMPLETED

  testpatt=$(echo $test | sed -e 's#(#/#g' -e 's#)##g')

  if [[ $testpatt == toplevel* ]]; then 
    STATUS=${testpatt/toplevel_/}
  else
    STATUS=$(basename $testpatt)
  fi

  [[ $STATUS == $testpatt ]]   && continue
  [[ $STATUS == INCOMPLETE ]]  && STATE=INCOMPLETE


  echo INFO: Set state/status to $STATE/$STATUS for $testpatt
  $MT_MEGATEST -set-state-status $STATE,$STATUS -runname $MT_RUNNAME -testpatt $testpatt

done < <($MT_MEGATEST -list-runs $MT_RUNNAME | grep Test:)

